### ISSUE TITLE
test in tests/test_denoise.py fail (install binary dependencies with dev/bootstrap.sh [muscle, usearch, ssearch])

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/bioy#15]
Multiple test fail, but here's an example:

```
$ ./testone -vv tests.test_denoise.TestDenoise.test01
test01 (tests.test_denoise.TestDenoise) ... DEBUG denoise 117 aligning cluster 1 len 4
ERROR

======================================================================
ERROR: test01 (tests.test_denoise.TestDenoise)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_denoise.py", line 33, in test01
    self.main([fa, '--clusters', uc, '--outfile', fa_out, '--limit', limit])
  File "tests/test_denoise.py", line 24, in main
    main(['denoise'] + [str(a) for a in arguments])
  File "bioy_pkg/scripts/main.py", line 36, in main
    return action(arguments)
  File "bioy_pkg/subcommands/denoise.py", line 150, in action
    for cluster, cons in pool.imap_unordered(align_and_consensus, enumerate(chunks, start = 1)):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 626, in next
    raise value
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 1 test in 0.185s

FAILED (errors=1)
```

**Comment by crosenth** [comment]
Stale
